apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-backend
  namespace: personal-blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-backend
  template:
    metadata:
      labels:
        app: blog-backend
    spec:
      containers:
        - name: blog-backend
          image: gendos123/personal-blog@sha256:05604fb45cd4a2ed3563d6d5a59a72bfc5ea00a09c3fc9c775a3b75a0f0f7b05
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: dockerhub-cred
