apiVersion: v1
kind: Service
metadata:
  name: blog-backend
  namespace: personal-blog
spec:
  type: NodePort
  selector:
    app: blog-backend
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
